### PR TITLE
Replaced CheckButton with Switch on Budgie Settings

### PR DESCRIPTION
**Pull request by fauzie811**
screenshot from 2014-12-14 05 39 24
screenshot from 2014-12-14 05 39 56
screenshot from 2014-12-14 05 40 03

### CODE REVIEW

**Comment by ryanleesipes** [comment]
For the purposes of looks, I prefer the switches. Granted some themes probably do have crappy switches. I'd like to see an example though of a theme that makes this look horrible.

**Comment by ikeydoherty** [comment]
The Evolve OS default, for a start. I can re-evaluate this with 3.14 now, cheers for bringing to attention. With 3.12 it wasnt gonna happen.

**Comment by ikeydoherty** [comment]
Case in point..
screenshot from 2015-02-01 15 57 07

Looks derpy with most themes. :/

**Comment by ryanleesipes** [comment]
I don't think it looks derpy. Just not clearly indicating which state it is
in.

**Comment by ikeydoherty** [comment]
No I mean the sizing, its centered and not right-aligned.

**Comment by ryanleesipes** [comment]
Ah, I see.

**Comment by ikeydoherty** [comment]
Meh I give in. Merging, thanks!

**Pull request merged**
