### PR TITLE
specify DesktopNames field in .desktop - refers #155

### PR DESCRIPTION
**Pull request by LeoIannacone**
More specifically:
 https://github.com/evolve-os/budgie-desktop/issues/155#issuecomment-73356841

It is really useful on Ubuntu based distributions.

### CODE REVIEW

**Comment by ikeydoherty** [comment]
Let's go for it.. cheers :)

**Comment by funnylookinhat** [comment]
This does fix the issue of having the correct applications and settings show up in the App Launcher and Control Panel.  However, it does not fix the issue of polkit-agent running ( #160 )

Tried the PR - no go.  I also tried editing `/etc/xdg/autostart/polkit-gnome-authentication-agent-1.desktop` to have: `OnlyShowIn=GNOME;XFCE;Unity;Budgie;`

**Comment by ikeydoherty** [comment]
@funnylookinhat try running that manually (the Exec line) and let me know whats printed out on IRC

**Comment by funnylookinhat** [comment]
For logging purposes:

```
budgie@budgie-VirtualBox:~$  /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1

(polkit-gnome-authentication-agent-1:3885): polkit-gnome-1-WARNING **: Unable to determine the session we are in: No session for pid 3885
```

Users in #ubuntu-gnome on Freenode suggested that the command should be failing anyways - i.e. a terminal shouldn't be able to run it.  Not sure why exactly.

**Comment by LeoIannacone** [comment]
Please, open a new issue with all this info... I will happy to help.

**Comment by funnylookinhat** [comment]
Hi @LeoIannacone - we're working on this one in #160

**Pull request merged**
